blueprint:
  name: Z2M IKEA styrbar 4 button custom actions
  description: Create actions for each button, for short and long press
  domain: automation
  input:
    remote:
      name: Styrbar-Remote Action Device
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: IKEA
              model: STYRBAR remote control
    action_on:
      name: On Button
      description: Action to run when SHORT press
      default: []
      selector:
        action: {}
    action_off:
      name: Off Button
      description: Action to run when SHORT press
      default: []
      selector:
        action: {}
    action_on_long:
      name: Brightness up Button
      description: Action to run when Long press
      default: []
      selector:
        action: {}
    action_off_long:
      name: Brightness down Button
      description: Action to run when Long press
      default: []
      selector:
        action: {}
    action_right:
      name: Right Button click
      description: Action to run when short press
      default: []
      selector:
        action: {}
    action_right_long:
      name: Right Hold Button
      description: Action to run when Long press
      default: []
      selector:
        action: {}
    action_left:
      name: Left Button
      description: Action to run when Short press
      default: []
      selector:
        action: {}
    action_left_long:
      name: Left Hold Button
      description: Action to run when Long press
      default: []
      selector:
        action: {}
mode: queued
max_exceeded: silent

trigger:
  - platform: device
    device_id: !input remote
    domain: mqtt
    type: action

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.subtype == 'on' }}"
        sequence: !input action_on
      - conditions:
          - condition: template
            value_template: "{{ trigger.subtype == 'off' }}"
        sequence: !input action_off
      - conditions:
          - condition: template
            value_template: "{{ trigger.subtype == 'brightness_move_up' }}"
        sequence: !input action_on_long
      - conditions:
          - condition: template
            value_template: "{{ trigger.subtype == 'brightness_move_down' }}"
        sequence: !input action_off_long
      - conditions:
          - condition: template
            value_template: "{{ trigger.subtype == 'arrow_right_click' }}"
        sequence: !input action_right
      - conditions:
          - condition: template
            value_template: "{{ trigger.subtype == 'arrow_right_hold' }}"
        sequence: !input action_right_long
      - conditions:
          - condition: template
            value_template: "{{ trigger.subtype == 'arrow_left_click' }}"
        sequence: !input action_left
      - conditions:
          - condition: template
            value_template: "{{ trigger.subtype == 'arrow_left_hold' }}"
        sequence: !input action_left_long
